옷장에 recycler view 달아놨습니다
Konkuk-LookUp/LookUp pull request #9
Opened 2023-11-27 17:28 UTC by songhyun9999

2023-11-28 11:20 UTC, 0703kyj requested changes
코멘트 확인해주세요~

2023-11-28 11:20 UTC, 0703kyj commented on app/src/main/java/com/example/lookup/view/closet/MyCloth.kt
> +data class MyCloth(var img: Int, var name:String): Serializable
서버에서 옷 모델 불러올려고 하면 이미지 파일명도 필요합니다! 그것만 추가하면 합쳐도 될 것 같아요~

2023-11-29 13:23 UTC, songhyun9999 commented on app/src/main/java/com/example/lookup/view/closet/MyCloth.kt
> +data class MyCloth(var img: Int, var name:String): Serializable
이미지 파일명이 뭘 얘기하는지 잘 모르겠어요

2023-11-29 14:01 UTC, 0703kyj commented on app/src/main/java/com/example/lookup/view/closet/MyCloth.kt
> +data class MyCloth(var img: Int, var name:String): Serializable
```suggestion
data class MyCloth(var img: Int, var name:String, var filename:String): Serializable
```
이렇게 MyCloth에 파일이름이 추가되어서 클릭했을 때, sharedPreference에 값 설정할 수 있어야 된다는 의미입니다! 현재는 서버에서 어떤 파일을 가져와야된다는 정보가 없어서 클릭 시에 아무런 동작을 할 수 가 없어요!
즉
```
PreferenceManager.setString(requireContext(),CLOTH_FILENAME,"white_sneakers.obj")
```
여기서 "white_sneakers.obj"대신에 들어갈 값도 MyCloth에서 가지고 있어야 된다는 의미입니다. 나중에 이부분을 data.filename으로 바꿔야 되고요

2023-11-30 05:40 UTC, 0703kyj approved these changes
.

2023-11-30 05:40 UTC, merged